apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qr2j6h90s-go 
  janus-idp.io/tekton: qr2j6h90s-go
  backstage.io/kubernetes-id: qr2j6h90s-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qr2j6h90s-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  