apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: qr2j6h90s-go-gitops
  description: This is GitOps manifest for qr2j6h90s-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: qr2j6h90s-go
    backstage.io/kubernetes-id: qr2j6h90s-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: qr2j6h90s-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:qr2j6h90s-go
